"""esquema inicial FASE 8

Revision ID: cd7bca5eb889
Revises: 
Create Date: 2026-08-30 17:34:16.982719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7bca5eb889'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frases_categoria'), 'frases', ['categoria'], unique=False)
    op.create_table('historial_traduccion',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('direccion', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('es_demo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_traduccion_creado_en'), 'historial_traduccion', ['creado_en'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_historial_traduccion_creado_en'), table_name='historial_traduccion')
    op.drop_table('historial_traduccion')
    op.drop_index(op.f('ix_frases_categoria'), table_name='frases')
    op.drop_table('frases')
    # ### end Alembic commands ###
